name: Update
on:
  schedule:
    - cron: "5 */8 * * *"
  workflow_dispatch:
jobs:
  run-script:
    name: Update
    runs-on: ubuntu-latest
    env:
      MOMOX_MEDIA_TOKEN: ${{ secrets.MOMOX_MEDIA_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm install
      - name: Run script
        run: npm run update
      - name: Save changes
        run: |-
          git config --global user.email "my-github-action@bot.com"
          git config --global user.name "my github action bot"
          git add --all
          git diff-index --quiet HEAD || git commit -m "Automatic update"
          git push
